### ISSUE TITLE
The app doesn't run with stable  v1.12.13+hotfix.5

### ISSUE THREAD

**Issue by humazed** [bernaferrari/color-studio#2]
Running with flutter v1.12.13+hotfix.5 the app just crashes with no error message.
I see you included a web folder which means it's built with the beta version at least.
which version of flutter should I use to run the app?

**Comment by Shubxam** [comment]
I can confirm this behavior.

**Comment by bernaferrari** [comment]
Uhhhh ohh. I'm testing in dev (1.13.5 framework revision 41a911099b) in macOS. Could you try in dev branch and tell me what happens?

I tried it here on the web and worked fine.
<p align="center"><img src="https://user-images.githubusercontent.com/351125/71501310-91f91d00-2848-11ea-8fd3-e43e7683140a.png" alt="ChangeDetection" height="400px"></p>

**Comment by jshvarts** [comment]
Possibly related: Running `gradlew build` in `android` getting build failure. 

```
lib/example/mdc/showcase.dart:173:27: Error: No named parameter with the name 'clipBehavior'.
                          clipBehavior: Clip.antiAlias,
                          ^^^^^^^^^^^^
../../development/flutter/packages/flutter/lib/src/widgets/container.dart:302:3: Context: Found this candidate, but the arguments don't match.
  Container({
  ^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

> Task :app:compileFlutterBuildDebug FAILED

FAILURE: Build failed with an exception.
```

**Comment by bernaferrari** [comment]
Thanks! @jshvarts 

I know what went wrong. ClipBehavior on Container was commited 24 days ago and is available since 1.13.0, but not on stable. I have just replaced it with something else. Could you all try again?!

https://github.com/flutter/flutter/commit/f68cdacdd5ae701de7c8e532342f91f85d5a071f#diff-26623f46f87b8f10fdcf148c2e53469a

**Comment by jshvarts** [comment]
Builds and runs fine in AS now!

`gradlew build` now gives me a test failure but at least I can build it in AS.

```
> Task :path_provider:testDebugUnitTest FAILED
io.flutter.plugins.pathprovider.StorageDirectoryMapperTest > testAndroidType_valid FAILED
    java.lang.IllegalArgumentException at StorageDirectoryMapperTest.java:28
3 tests completed, 1 failed
FAILURE: Build failed with an exception.
```

**Comment by bernaferrari** [comment]
.___. I'll give a look into this (plus, the signing issues with gradle). Thanks!

**Comment by bernaferrari** [comment]
Issues with Gradle solved. After initial `flutter pub get` it should work without errors in Android and iOS (after `pod install`).

**Comment by jshvarts** [comment]
hmmm...still see the same test failure

**Comment by bernaferrari** [comment]
I'm not sure where that is coming from. Couldn't find anything. But as long as you can run it, it should be fine. Feel free to tell if anything weird ever happens again. I'm also setting up GitHub Actions with the stable release of Flutter, so this issue never happens with you or anyone else ever again.
