### ISSUE TITLE
Shows 'Flutter Demo' as title in recent apps screen

### ISSUE THREAD

**Issue by vishnumad** [bernaferrari/color-studio#3]
![Screenshot](https://user-images.githubusercontent.com/3137711/71520383-765e3880-2881-11ea-91ca-e5142fb26da6.png)

This is on Android 8.0 and LG's skin

**Comment by bernaferrari** [comment]
Hahaha! Thanks! I'll fix this.

I'm using Android 9 and Android doesn't show anything in recents app screen anymore, that's why I didn't see it.
